### ISSUE TITLE
Can I obtain help, build command saying error

### ISSUE THREAD

**Issue by RowanSkie** [tirea/fwew#5]
I'm on Windows, and I'm installing this app via the compile and install from source code option, I have Go and Git installed, and here's what happens.

> PS C:\Users\Zuni> cd go\src\
> PS C:\Users\Zuni\go\src> go get github.com/c-bata/go-prompt
> PS C:\Users\Zuni\go\src> git clone https://github.com/tirea/fwew
> Cloning into 'fwew'...
> remote: Enumerating objects: 54, done.
> remote: Counting objects: 100% (54/54), done.
> remote: Compressing objects: 100% (38/38), done.
> remote: Total 1810 (delta 23), reused 39 (delta 13), pack-reused 1756R
> Receiving objects: 100% (1810/1810), 61.09 MiB | 1.25 MiB/s, done.
> Resolving deltas: 100% (969/969), done.
> PS C:\Users\Zuni\go\src> cd fwew
> PS C:\Users\Zuni\go\src\fwew> go build -o $HOME\fwew.exe .\fwew.go
> # command-line-arguments
> .\fwew.go:94:26: undefined: Word
> .\fwew.go:96:13: undefined: Word
> .\fwew.go:97:15: undefined: Word
> .\fwew.go:114:12: undefined: InitWordStruct
> .\fwew.go:191:29: undefined: Word
> .\fwew.go:328:22: undefined: Word
> .\fwew.go:339:46: undefined: Word
> .\fwew.go:452:33: undefined: Word
> .\fwew.go:603:35: undefined: Word
> .\fwew.go:631:22: undefined: Word
> .\fwew.go:114:12: too many errors
> PS C:\Users\Zuni\go\src\fwew>

Is there something wrong? Is my Go and Git programs wrong version?

**Comment by tirea** [comment]
Hey there! 

In case someone else comes across this in the future, the build is working, and so are your versions of Go and Git. I simply needed to rewrite the Windows build instructions in the README. (which I have just now done. If the updated instructions don't work, feel free to re-open this issue and comment here.)

EDIT: The problem here is that I restructured the project and forgot to update the build instructions accordingly in the README. With how `go build` works, given the new structure of the project, the `.\fwew.go` argument breaks it because it only tries to build that one file and ignores the other source files. Previously, `fwew.go` explicitly imported those from other folders/packages in the project. Now, they are all in the root project directory and in the same Go package `main`. `go build` seems to build and link all files in the `main` package in the current directory by default if not supplied any argument about which source file to compile.

Here is what Windows users would need to do (at time of this writing):

In a Powershell window:
```
cd $HOME                                # Start at home folder
mkdir go\src                            # Make a folder for all Go source code
setx GOPATH %USERPROFILE%\go            # Set GOPATH variable to newly created go folder
```
Then in new Powershell window:
```
cd go\src\                              # This is where we will download the fwew source code
go get github.com/c-bata/go-prompt      # Install the go-prompt library (fwew depends on this library)
git clone https://github.com/tirea/fwew # Download the code
cd fwew                                 # Go to where the code is before trying to build it
go build -o fwew.exe                    # compile
cp -Recurse .\.fwew $HOME\              # copy data file folder to your user's home folder
```
Then add the fwew folder (which will be something like `C:\Users\USERNAME\go\src\fwew`) to your PATH. (Search for Environment Variables from the main Windows Search bar to find the setting) This will enable you to just type `fwew` instead of `.\fwew.exe` or `C:\Path\to\fwew\fwew.exe` or whatever each time.

You may want to run `/update` from inside `fwew` in order to update the dictionary file after install.

Additionally, I've heard that Microsoft has finally added support for UTF-8 character set in the all-new Windows 10 Terminal app. From here, it's your choice if you want to use that or Powershell for using `fwew` after install.
